Use project geometry center if issue geometry is nil (#23)
gtt-project/redmine_gtt_print pull request #24
Opened 2023-04-06 09:14 UTC by sanak

Fixes #23

Changes proposed in this pull request:
- Use project geometry center if issue geometry is nil.

@gtt-project/maintainer

2023-04-12 03:08 UTC, mopinfish requested changes
@sanak 一つコメントしたのでお手すきの際にご確認ください。

2023-04-12 03:08 UTC, mopinfish commented on lib/redmine_gtt_print/issue_to_json.rb
> +      else
条件式内のコードの重複が気になったので、下記のような書き方にしてはいかがでしょうか。

```
## Get GeoData from Issue or Project
data = @issue.geodata_for_print || Project.find(@issue.project_id).geodata_for_print
if data
  geojson = data[:geojson] || []
  json[:attributes][:map] = self.class.map_data(data[:center], geojson,
          scale, basemap_url)
end
```

2023-04-14 09:48 UTC, mopinfish commented on lib/redmine_gtt_print/issue_to_json.rb
> +      else
了解しました。ではこの実装で問題ないと思います。

2023-04-14 09:49 UTC, mopinfish commented
LGTM

2023-04-14 09:54 UTC, mopinfish approved these changes

2023-04-14 09:56 UTC, sanak commented
Thanks!

2023-04-14 09:56 UTC, merged