Support synchronize printing
gtt-project/redmine_gtt_print pull request #34
Opened 2024-07-02 04:06 UTC by sanak

Supports #33.

Changes proposed in this pull request:
- [x] Support sync print downloading.
- [ ] Fix tests.
- [ ] Check AWS Lambda setup.

@gtt-project/maintainer

2024-07-18 06:26 UTC, mopinfish requested changes
ご確認お願いします。

2024-07-18 06:50 UTC, sanak commented on app/controllers/gtt_print_jobs_controller.rb
> +        r = RedmineGttPrint.mapfish.print job, request.referer, request.user_agent
@mopinfish こちらですが、戻り値の型が非同期時は `CreateJobResult = ImmutableStruct.new(:success?, :ref)`、同期時は `PrintResult = ImmutableStruct.new(:pdf, :error)` となって異なってややこしいかなと思い、分岐していました。

ちなみに、以下のクラス抽象化の件とも関連しますが、戻り値の型が違う場合はメソッド名を分けた方が良いですか？ (非同期時は `print_async`, 同期時は `print_sync` など)

2024-07-18 07:05 UTC, sanak commented on app/views/hooks/_print_issue_form.html.erb
> +<% is_sync = RedmineGttPrint.settings['enable_sync_printing'] == 'true' %>
@mopinfish 上記、了解しました。🙆‍♂️
`is_sync` は具象クラスのインスタンスを作成している `RedmineGttPrint` モジュールでも必要になりそうなので、以下のようにクラスメソッド `is_sync?` を追加し、 コントローラ側で `@is_sync = RedmineGttPrint.is_sync?` として設定する形にしようかと考えています。
```diff
--- a/lib/redmine_gtt_print.rb
+++ b/lib/redmine_gtt_print.rb
@@ -24,17 +24,27 @@ module RedmineGttPrint
     (settings['tracker_config'] || {})[tracker.id.to_s]
   end
 
+  def self.is_sync?
+    settings['enable_sync_printing'] == 'true'
+  end
+
   def self.layouts_for_tracker(tracker)
     mapfish.layouts tracker_config tracker
   end
 
   def self.mapfish
     RequestStore.store[:mapfish] ||=
-      RedmineGttPrint::Mapfish.new(
-        host: settings['default_print_server'],
-        timeout: settings['default_print_server_timeout'],
-        is_sync: settings['enable_sync_printing']
-      )
+      if !is_sync?
+        RedmineGttPrint::MapfishAsync.new(
+          host: settings['default_print_server'],
+          timeout: settings['default_print_server_timeout']
+        )
+      else
+        RedmineGttPrint::MapfishSync.new(
+          host: settings['default_print_server'],
+          timeout: settings['default_print_server_timeout']
+        )
+      end
   end
```

2024-07-18 07:23 UTC, sanak commented on lib/redmine_gtt_print/mapfish.rb
>      CreateJobResult = ImmutableStruct.new(:success?, :ref)
@mopinfish 上記コメントありがとうございます。 🙇
以下について念のため確認頂けると助かります。
1. `is_sync?` による分岐がないメソッドについては抽象クラスに実装し、それ以外の分岐の必要なメソッドについては以下を参考に実装してしまって問題ありませんか？
   * [RubyでJavaのインターフェースっぽいことをする - GitPress.io](https://gitpress.io/@rhiroe/ruby-interface)
2. 上のJavaのサンプルコードでは、ファクトリークラス(`DocumentFactory `)が作成されていますが、以下のコメント記載のように、インスタンス作成時に単純に `is_sync?` の値に基づいて該当クラスをnewするのみで問題ありませんか？
    ```diff
    --- a/lib/redmine_gtt_print.rb
    +++ b/lib/redmine_gtt_print.rb
       def self.mapfish
         RequestStore.store[:mapfish] ||=
    -      RedmineGttPrint::Mapfish.new(
    -        host: settings['default_print_server'],
    -        timeout: settings['default_print_server_timeout'],
    -        is_sync: settings['enable_sync_printing']
    -      )
    +      if !is_sync?
    +        RedmineGttPrint::MapfishAsync.new(
    +          host: settings['default_print_server'],
    +          timeout: settings['default_print_server_timeout']
    +        )
    +      else
    +        RedmineGttPrint::MapfishSync.new(
    +          host: settings['default_print_server'],
    +          timeout: settings['default_print_server_timeout']
    +        )
    +      end
       end
    ```

2024-07-18 07:40 UTC, mopinfish commented on lib/redmine_gtt_print/mapfish.rb
>      CreateJobResult = ImmutableStruct.new(:success?, :ref)
@sanak 

> is_sync? による分岐がないメソッドについては抽象クラスに実装し、それ以外の分岐の必要なメソッドについては以下を参考に実装してしまって問題ありませんか？

抽象クラスというか、元の `lib/redmine_gtt_print/mapfish.rb` に実装をそのまま残す形で良いと思います。


Javaの例をAIが出力してしまったのでそのまま記載したことで混乱を招いてしまったようですみません。

今回はAbstract, Interfaceといった言語の文法上の制約は別に気にしなくて良いです。

上記コメントで伝えたかったことは、要は `is_sync?` か否かによって  print, get_status, get_print, request_print に必要な処理を二つのサブクラスに分けてそれを呼び出すようにすれば良いと思います。その分離ができていればどのような実装であってもRubyのシンプルなシンタックスで実現できていれば問題ありません。

> 以下のように、インスタンス作成時に単純に is_sync? の値に基づいて該当クラスをnewするのみで問題ありませんか？

おっしゃる通り、ここでのポイントは `is_sync?` によってnew するサブクラスが切り替えられていればOKです。

2024-07-18 07:42 UTC, mopinfish commented on app/views/hooks/_print_issue_form.html.erb
> +<% is_sync = RedmineGttPrint.settings['enable_sync_printing'] == 'true' %>
上記了解です。

2024-07-18 07:42 UTC, sanak commented on lib/redmine_gtt_print/mapfish.rb
>      CreateJobResult = ImmutableStruct.new(:success?, :ref)
@mopinfish 上記、了解しました。
確認頂き、ありがとうございます！ :bow:

2024-07-18 07:43 UTC, mopinfish commented on app/controllers/gtt_print_jobs_controller.rb
> +        r = RedmineGttPrint.mapfish.print job, request.referer, request.user_agent
> ちなみに、以下のクラス抽象化の件とも関連しますが、戻り値の型が違う場合はメソッド名を分けた方が良いですか？ (非同期時は print_async, 同期時は print_sync など)

むしろ `print` というメソッドで内部が同期か非同期かを特に気にすることなくカプセル化できていると思うのでそのままで良いと思います。

2024-07-18 07:47 UTC, sanak commented on app/controllers/gtt_print_jobs_controller.rb
> +        r = RedmineGttPrint.mapfish.print job, request.referer, request.user_agent
なるほど、了解です。  
ご指摘どおり、ブロックの外側に出して一度に取得し、その後に `is_sync?` (=`@is_sync`)の値に応じて、render/send処理を切り替えるようにします。

2024-07-19 03:08 UTC, sanak commented on app/views/hooks/_print_issue_form.html.erb
> +<% is_sync = RedmineGttPrint.settings['enable_sync_printing'] == 'true' %>
@mopinfish 下記ですが、確認したところ、GTT Printプラグインでオーバーライドしていない IssuesController側でインスタンス変数を定義する必要があるようで、少し大変になりそうでした。

> erbテンプレート内での条件判定は可読性に難があるため、コントローラ側でフラグ変数をアサインする形の方が良いように思いますがいかがでしょうか？

上記より、以下のような形とさせて頂きましたので、確認をお願いします。
```diff
-<% is_sync = RedmineGttPrint.settings['enable_sync_printing'] == 'true' %>
+<% is_sync = RedmineGttPrint.is_sync? %>
```

2024-07-19 03:19 UTC, sanak commented on lib/redmine_gtt_print/mapfish_sync.rb
> +      str = URI.encode_www_form_component(layout)
@mopinfish `mapfish.rb` クラスを継承して、 `mapfish_async.rb` と `mapfish_sync.rb` クラスを作成しましたが、こちらの `request_print` プライベートメソッドのみ、メソッド内前半の箇所が重複しているのが少し気になりました。処理としては、 `str` と `headers` を生成するところまでが共通なので、別のプライベートメソッド(`prepare_headers_and_layout` など)にまとめて親の `mapfish.rb` クラス側に移動した方が良いですか？

なお、テストが失敗しているため、引き続きそちらの対応も行っていく予定です。
https://github.com/gtt-project/redmine_gtt_print/actions/runs/10001936673/job/27646443710#step:17:79

2024-07-26 03:09 UTC, mopinfish commented on lib/redmine_gtt_print/mapfish_sync.rb
> +      str = URI.encode_www_form_component(layout)
@sanak 

> 別のプライベートメソッド(prepare_headers_and_layout など)にまとめて親の mapfish.rb クラス側に移動した方が良いですか？

そうですね、親クラスのプライベートメソッドとして切り出せると可読性の向上と重複排除ができて良さそうに思います。

2024-07-26 03:15 UTC, mopinfish reviewed
@sanak 一部コメント追加させていただきましたので、お手すきの際にご確認をお願いいたします。

2024-07-26 03:15 UTC, mopinfish commented on lib/redmine_gtt_print/mapfish_async.rb
> +      if !referer.nil?
些細な変更点ですが、ここでのifブロックは下記のように後置if形式を使うと、 `header` という変数に対する値をセットしていることが一見して分かりやすくなりそうに思いましたがいかがでしょうか。

`nil?` ではないことを確認する場合、 `present?` を使った方が反転演算子を使わなくて済むのでより判定意図が伝わりやすくなりそうに思いますがいかがでしょうか。

```
      headers = {
        'Content-Type' => 'application/json'
      }
      headers['Referer'] = referer if referer.present?
      headers['User-Agent'] = user_agent  if user_agent.present?
```

2024-07-26 04:22 UTC, sanak commented on lib/redmine_gtt_print/mapfish_sync.rb
> +      str = URI.encode_www_form_component(layout)
@mopinfish 確認ありがとうございます。上記の方、対応を進めていきます。

2024-07-26 04:22 UTC, sanak commented on lib/redmine_gtt_print/mapfish_async.rb
> +      if !referer.nil?
こちらも了解しました。
上記で修正するようにします。

2024-07-26 05:36 UTC, sanak commented on app/views/hooks/_print_issue_form.html.erb
> +<% is_sync = RedmineGttPrint.settings['enable_sync_printing'] == 'true' %>
こちら特にコメントありませんでしたので、Resolveしておきます。

2024-07-26 05:37 UTC, sanak commented on app/controllers/gtt_print_jobs_controller.rb
> +        r = RedmineGttPrint.mapfish.print job, request.referer, request.user_agent
こちら対応済みのため、Resolveしておきます。

2024-07-26 05:38 UTC, sanak commented on lib/redmine_gtt_print/mapfish.rb
>      CreateJobResult = ImmutableStruct.new(:success?, :ref)
こちら対応済みのため、Resolveしておきました。

2024-07-26 06:00 UTC, sanak commented on lib/redmine_gtt_print/mapfish_async.rb
> +      if !referer.nil?
@mopinfish コミット(https://github.com/gtt-project/redmine_gtt_print/pull/34/commits/517a1c48674a85c52cf8955c5223c57bf797ed10)で対応しましたので、再度確認をお願いします。

2024-07-26 06:00 UTC, sanak commented on lib/redmine_gtt_print/mapfish_sync.rb
> +      str = URI.encode_www_form_component(layout)
@mopinfish コミット(https://github.com/gtt-project/redmine_gtt_print/pull/34/commits/517a1c48674a85c52cf8955c5223c57bf797ed10) で対応しましたので、再度確認をお願いします。

2024-07-26 06:35 UTC, mopinfish approved these changes
@sanak Approveいたしました。

2024-07-26 06:48 UTC, sanak commented
@mopinfish ありがとうございます！
`1.1-stable` ブランチまでマージします。

2024-07-26 06:48 UTC, merged